# Generated by Django 5.2.4 on 2025-07-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="image_url",
        ),
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ads/", verbose_name="Изображение"
            ),
        ),
    ]
